### ISSUE TITLE
[优化建议]: 新增繁體中文介面支持

### ISSUE THREAD

**Issue by ashun-kaede** [Mereithhh/vanblog#348]
### 功能概述 | Describe the feature

希望可以新增繁體功能支持，或者繁簡傳換功能按鈕。

我剛剛嘗試透過自定義腳本自動進行繁簡轉換。
但由於只有在畫面重整的時候載入腳本，切畫nav的時候不會載入。不知道這方面是否有其他解決辦法?

**Comment by k1dave6412** [comment]
我目前是先這樣，將就用  
我看 i18n 有在 roadmap 可能要等作者更新了

```css
@font-face {
    font-family: "PingFang SC";
    src: url("https://blog.k1dav.fun/static/PingFang-SC-Regular.ttf");
    font-weight: normal;
    font-style: normal;
}
body {
    font-family: "PingFang SC";
    font-variant-east-asian: traditional;
}
```
