### ISSUE TITLE
[优化建议]:  伪静态支持

### ISSUE THREAD

**Issue by JIeJaitt** [Mereithhh/vanblog#416]
### 功能概述 | Describe the feature

文章后带上 `.html`

**Comment by CornWorld** [comment]
可以考虑在 caddy 配置文件(caddyfile)内添加相关内容

**Comment by JIeJaitt** [comment]
@CornWorld 这个具体我不太懂，可以参考下其他blog 系统是怎么弄这块的，另外大佬就是我们vanblog是没有代码块横向滚动的，在小屏幕上看代码会比较难受，希望优化。
ps，我通过在后台自定义css暂时性的解决了这个问题：
```css
.hljs {
    white-space: pre !important; /* 保持空白符号，允许正常的换行 */
    overflow-x: auto !important; /* 在内容超出时显示水平滚动条 */
    display: block !important; /* 确保元素是块级元素 */
    max-width: 100% !important; /* 限制最大宽度，防止溢出 */
    padding: 0.5em !important; /* 适当的内边距 */
}

/* 覆盖滚动条样式，使其不可见 */
.code-block-wrapper::-webkit-scrollbar,
.code-block-wrapper pre::-webkit-scrollbar,
.code-block-wrapper code::-webkit-scrollbar {
    width: 0 !important; /* 对于垂直滚动条 */
    height: 0 !important; /* 对于水平滚动条 */
}
```
